using Microsoft.EntityFrameworkCore;
using Bangazon.Models;

namespace BangazonCLI.Data
{
    public class BangazonCLIContext : DbContext
    {
        public BangazonCLIContext(DbContextOptions<BangazonCLIContext> options)
            : base(options)
        { }

        public DbSet<Customer> Customer { get; set; }
        // public DbSet<PaymentType> PaymentType { get; set; }
        // public DbSet<Product> Product { get; set; }
        // public DbSet<Order> Order { get; set; }
       
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        // If a model has a date field that should be generated by the database  
        }
    }
}